apiVersion: v1
kind: Service
metadata:
  name: {{ include "mawazo.fullname" . }}
  labels:
    {{- include "mawazo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "mawazo.selectorLabels" . | nindent 4 }}
